[package]
name = "coin_flip_simulation"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Cooper"]
description = "A coin flipping simulation, in preperation for a upcoming probability crate"
repository = "https://github.com/oberon-git/coin_flip_simulation"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
